In [1]:
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import h5py

# from scipy.stats import binned_statistic_2d
# from scipy.ndimage import gaussian_filter
from matplotlib.colors import LogNorm
from matplotlib.colors import SymLogNorm
import matplotlib
import matplotlib.cm as cm

# from abacusnbody.analysis.tsc import tsc_parallel
import time

from astropy.cosmology import FlatLambdaCDM
import astropy.units as u

# Import packages

sys.path.append('../src/')
# from filter_utils import *
from utils import ksz_from_delta_sigma, arcmin_to_comoving, comoving_to_arcmin
from stacker import SimulationStacker
from halos import select_massive_halos
from mask_utils import get_cutout_indices_3d, sum_over_cutouts

sys.path.append('../../illustrisPython/')
import illustris_python as il # type: ignore

import yaml
import argparse
from pathlib import Path

In [2]:
from loadIO import load_as_dict

In [36]:
stacker = SimulationStacker('TNG300-2', 67, z=0.5,)
# stacker = SimulationStacker('m50n512', 125, z=0.5, simType='SIMBA', feedback='s50')

In [37]:
haloes = stacker.loadHalos()
haloMass = haloes['GroupMass']
haloRad = haloes['GroupRad']
haloPos = haloes['GroupPos']

# subHaloes = stacker.loadSubHalos(stacker.simType)

In [ ]:
# halo_path = stacker.simPath + 'catalogs/' + stacker.sim + '_' + str(stacker.snapshot) + '.hdf5'
# subHaloes_cat = load_as_dict(halo_path, 'galaxy_data')
# Haloes_cat = load_as_dict(halo_path, 'halo_data')

In [ ]:
# # subHaloes_cat['dicts']['masses.total'][:1000]
# subHaloes_cat['dicts']['masses.stellar'][:100]

# subHaloes_cat['parent_halo_index'][:100]

In [39]:
snapshot = 67
sim_path = stacker.simPath


haloes_cat = il.groupcat.loadHalos(sim_path, snapshot)
subHaloes_cat = il.groupcat.loadSubhalos(sim_path, snapshot)

subHaloMStar = subHaloes_cat['SubhaloMassType'][:, 4] * 1e10
subHalo_MassInd = np.argsort(subHaloMStar)[::-1]  # Indices that would sort the stellar masses in descending order

In [40]:
subHaloes_cat['SubhaloID']

KeyError: 'SubhaloID'

In [ ]:
# haloes_cat['GroupFirstSub']

In [ ]:
# print(subHaloes_cat.keys())

In [ ]:
subHaloMStar = subHaloes_cat['SubhaloMassType'][:, 4] * 1e10
subHalo_MassInd = np.argsort(subHaloMStar)[::-1]  # Indices that would sort the stellar masses in descending order

In [ ]:
subHalo_massind = np.argsort(subHaloes_cat['SubhaloMassType'][:, 4])



SubhaloGrNr = subHaloes_cat['SubhaloGrNr']
unique_sub_grnr, firsts = np.unique(SubhaloGrNr, return_index=True)
# Firsts is the index of the first subhalo for each unique group number, the 'centrals'




In [14]:
firsts.shape

(2264299,)

In [12]:
(subHaloes_cat['SubhaloMassInRad'][firsts] / haloes_cat['GroupMass'][unique_sub_grnr])[:10]

array([0.0992085 , 0.07381929, 0.1252094 , 0.03093589, 0.03326221,
       0.18199947, 0.02323571, 0.1468303 , 0.04975875, 0.0471012 ],
      dtype=float32)

In [15]:
subHaloes_cat['SubhaloGrNr'].shape

(2722879,)

In [22]:
subHaloes_cat['SubhaloPos'][0:935]

array([[ 42574.25 ,  47247.23 , 149054.84 ],
       [ 42139.15 ,  48002.293, 148109.53 ],
       [ 42257.76 ,  46066.754, 149806.34 ],
       ...,
       [ 42105.46 ,  49377.594, 148583.3  ],
       [ 44055.387,  48836.805, 148596.4  ],
       [ 43649.992,  48149.87 , 147100.86 ]], dtype=float32)

In [10]:
subHaloes_cat['SubhaloFlag']

array([ True,  True,  True, ...,  True,  True,  True])

In [4]:
haloes

{'GroupMass': array([8.8877859e+14, 5.9064954e+14, 5.8403220e+14, ..., 2.3248118e+09,
        8.4717650e+09, 7.5765699e+09], dtype=float32),
 'GroupPos': array([[ 42574.25 ,  47247.23 , 149054.84 ],
        [ 80376.25 , 121892.664, 195644.92 ],
        [ 44977.445,  53595.547, 144812.03 ],
        ...,
        [186478.27 ,   8593.454, 125209.21 ],
        [183667.2  , 146781.22 ,  43323.44 ],
        [182763.27 ,  42493.277, 122267.   ]], dtype=float32),
 'GroupRad': array([2241.3843 , 1727.8457 , 1912.791  , ...,    0.     ,   41.82621,
          35.00451], dtype=float32)}